import type { Metadata } from 'next';
import { Montserrat, Exo_2 } from 'next/font/google';
import { AppProvider } from '@/app/providers';
import './globals.css';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-montserrat',
});

const exo2 = Exo_2({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-exo-2',
});

export const metadata: Metadata = {
  title: 'Dfluid App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${exo2.variable} antialiased`}>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
