import type { Metadata } from 'next';
import { Exo_2 } from 'next/font/google';
import './globals.css';

const exo2 = Exo_2({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-exo-2',
});

export const metadata: Metadata = {
  title: 'Dfluid App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${exo2.variable} antialiased`}>{children}</body>
    </html>
  );
}
